name = "MIMIC"
license = "MIT"
description = "Theme inspired by gohugo.io"
homepage = "https://github.com/mit-lcp/mimic-theme"
tags = ["landing page", "hugo"]
min_version= 0.12

[author]
     name = "Alistair Johnson"

[source]
    author =  "crakjie"
    homepage = "https://github.com/crakjie/hugo-base-theme"

[original]
    author =  "spf13"
    homepage = "https://spf13.com"

